%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOMplot_compIV.m
% Author: Shutian Xue
% Date: August 27, 2025
% ------------------------------------------------------------
% Purpose:
%  Visualize the outputs generated by OOD_NOM_Trialwise_compIV.m.
%  This includes distributions of the internal variable (IV), trial counts per bin,
%  and performance metrics across iterations, as well as the 2D kernel visualization.
%
% Usage:
%  Run this script after executing OOD_NOM_Trialwise_compIV.m and loading its output.
%  The script expects variables such as data_allB, data_metrics_allIter, kernel2D, axis_tuning,
%  axisTicks_tuning, axisTL_tuning, and namesMetrics to be available in the workspace.
%
% Inputs:
%  - data_allB: cell array containing IV, bin counts, and trial data for each iteration
%  - data_metrics_allIter: matrix of performance metrics for each iteration
%  - kernel2D: 2D kernel matrix
%  - axis_tuning, axisTicks_tuning, axisTL_tuning: axis info for kernel plot
%  - namesMetrics: cell array of metric names
%
% Outputs:
%  - Figures visualizing IV distributions, bin counts, performance metrics, and kernel2D
%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Visualizes the output generated by OOD_NOM_Trialwise_compIV.m
% This script is intended to be called after running OOD_NOM_Trialwise_compIV.m
% It loads the saved output and generates plots for IV distribution, bin counts, and performance metrics.

set(0, 'DefaultFigureVisible', 'off') % avoid printing figures on the desktop


%% Figure 1: Performance Metrics across Iterations
figure('Position', [100, 100, 2e3, 2e3])
for iMetric = 1:nMetrics
    subplot(3, 4, iMetric), hold on

    [metric_med, ~, ~, metric_sem_neg, metric_sem_pos] = getCI(data_metrics_allIter(:, :, iMetric), 1, 1);

    for iDataset = 1:nDatasets % iDataset: 1=full, 2=tmpl, 3=train, 4=test
        if iDataset==1, color_face = 'k'; else, color_face = 1-ratio_split(iDataset-1)*ones(1,3); end
        bar(iDataset, metric_med(iDataset), 'EdgeColor', 'k', 'FaceColor', color_face)
        errorbar(iDataset, metric_med(iDataset), metric_sem_neg, metric_sem_pos, 'k', 'capsize', 0)
    end

    xticks(1:nDatasets)
    xticklabels(namesDataset_full)
    % ylabel(namesMetrics{iMetric})
    title(namesMetrics{iMetric})
    
    % Set y-axis limits based on metric type
    switch iMetric
        % metrics: [dprime, criterion, [pC, pHit, pFA], nanmean(respC), pYES, mean(1./contrast), median(RT)];
        case 1, ylimits = [0,2]; yline(dprime_theo, 'k--'); % dprime
        case 2, ylimits = [-1,1]; yline(0, 'k--'); % criterion
        case 3, ylimits = [0,1]; yline(.7, 'k--'); % pC; pC_titrate = 0.7 (defined in OOD_sim)
        case 4, ylimits = [.5, 1]; % pHit
        case 5, ylimits = [0, .5]; % pFA
        case 6, ylimits = [.5, 1]; % pA
        case 7, ylimits = [.5, 1]; % pA1
        case 8, ylimits = [.5, 1]; % pA0
        case 9, ylimits = [0, 1]; yline(.5, 'k--'); % pYES
        case 10, ylimits = [2, 3]; % CS
        case 11, ylimits = [0, .5]; % RT
    end
    ylim(ylimits)
end

set(findall(gcf, '-property', 'fontsize'), 'fontsize', 15)
set(findall(gcf, '-property', 'linewidth'), 'linewidth', 2)

sgtitle(sprintf('Figure 1. Measured metrics (Ave across %d iterations +- 68%% CI)\n%s (Loc%d ModelA%d %s)', ...
    nIter, subjName, iLocComb, iModelA, namesModelA{iModelA}))
saveas(gcf, sprintf('%s/1MetricMeasured_L%d_A%d.jpg', nameFolder_Figures_perSubj, iLocComb, iModelA))

%% Figure 2: 2D Kernel
template_tmpl_ave = squeeze(mean(template_tmpl_allIter, 1));
template_full_ave = squeeze(mean(template_full_allIter, 1));

figure('Position', [100, 100, 2e3, 2e3])

subplot(2,3,1), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_ideal), axis square, colorbar, %clim([0, .2])
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('True template')

subplot(2,3,2), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_tmpl_ave), axis square, colorbar, %clim([0, .2])
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('Template derived from TRAINING trials')

subplot(2,3,3), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_tmpl_ave-template_ideal), axis square, colorbar
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('Difference with the true template')

subplot(2,3,4), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_tmpl_ave-template_full_ave), axis square, colorbar
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('Full template minus training template')

subplot(2,3,5), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_full_ave), axis square, colorbar, %clim([0, .2])
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('Template derived from ALL trials')

subplot(2,3,6), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_full_ave-template_ideal), axis square, colorbar
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('Difference with the true template')

set(findall(gcf, '-property', 'fontsize'), 'fontsize', 15)
set(findall(gcf, '-property', 'linewidth'), 'linewidth',2)

% Calculate Pearson's corr
r_allIter = nan(nIter, 1);
p_allIter = r_allIter;
for iIter = 1:nIter
    kA = template_full_allIter(iIter, :, :);
    kA = kA(:);
    kB = template_ideal(:);
    [r, p] = corr(kA, kB);
    r_allIter(iIter) = r;
    p_allIter(iIter) = p;
end
[r_med, ~, ~, r_SEM] = getCI(r_allIter, 1, 1);
[p_med, ~, ~, p_SEM] = getCI(p_allIter, 1, 1);

sgtitle(sprintf('Figure 2. Recovered template\n%s (L%d, ModelA%d %s, nIter=%d)\nAveraged Pearson''s corr: r=%.2f (%.2f), p=%.3f (%.2f)', ...
    subjName, iLocComb, iModelA, namesModelA{iModelA}, nIter, r_med, r_SEM, p_med, p_SEM))

saveas(gcf, sprintf('%s/2Template_L%d_A%d.jpg', nameFolder_Figures_perSubj, iLocComb, iModelA))

%% Figure 3. Plot marg and margPred, print R2 and params in the title
[margORI_med, ~, ~, margORI_sem] = getCI(margORI_allIter, 1, 1);
[margSF_med, ~, ~, margSF_sem] = getCI(margSF_allIter, 1, 1);

[margPred_ORI_med, ~, ~, margPred_ORI_sem] = getCI(margPred_ORI_allIter, 1, 1);
[margPred_SF_med, ~, ~, margPred_SF_sem] = getCI(margPred_SF_allIter, 1, 1);

[margParam_ORI_med, ~, ~, margParam_ORI_sem] = getCI(margParams_ORI_allIter, 1, 1);
[margParam_SF_med, ~, ~, margParam_SF_sem] = getCI(margParams_SF_allIter, 1, 1);

[margR2_ORI_med, ~, ~, margR2_ORI_sem] = getCI(margR2_ORI_allIter, 1, 1);
[margR2_SF_med, ~, ~, margR2_SF_sem] = getCI(margR2_SF_allIter, 1, 1);

figure('Position', [0 0 1e3 1e3])
% ORI tuning (training set)
subplot(2,2,1); hold on;
plot(xORI, margORI_med(1, :), 'ko-', 'MarkerFaceColor', 'w');
plot(xORI, margPred_ORI_med(1, :), 'k-', 'LineWidth', 2);
xline(0, 'k--', 'LineWidth', 1); % ORI=0
yline(0, 'k--', 'LineWidth', 1); % Marginalized kernel=0
title(sprintf('ORI tuning function (training set)\nR2=%.2f (+-%.2f)| Params=[%s ]', margR2_ORI_med(1), margR2_ORI_sem(1), num2str(margParam_ORI_med(1, :), ' %.2f')));
xlabel('Orientation (deg)'); ylabel('Amplitude');
yticks(-.1:.1:1)

% ORI tuning (full set)
subplot(2,2,3); hold on;
plot(xORI, margORI_med(2, :), 'ko-', 'MarkerFaceColor', 'w');
plot(xORI, margPred_ORI_med(2, :), 'k-', 'LineWidth', 2);
xline(0, 'k--', 'LineWidth', 1); % ORI=0
yline(0, 'k--', 'LineWidth', 1); % Marginalized kernel=0
title(sprintf('ORI tuning function (full set)\nR2=%.2f (+-%.2f)| Params=[%s ]', margR2_ORI_med(2), margR2_ORI_sem(2), num2str(margParam_ORI_med(2, :), ' %.2f')));
xlabel('Orientation (deg)'); ylabel('Amplitude');
yticks(-.1:.1:1)

% SF tuning (training set)
subplot(2,2,2); hold on;
plot(xSF, margSF_med(1, :), 'ko-', 'MarkerFaceColor', 'w');
plot(xSF, margPred_SF_med(1, :), 'k-', 'LineWidth', 2);
xline(1, 'k--', 'LineWidth', 1); % SF=2 cpd
yline(0, 'k--', 'LineWidth', 1); % Marginalized kernel=0
title(sprintf('SF tuning function (training set)\nR2=%.2f (+-%.2f)| Params=[%s]', margR2_SF_med(1), margR2_SF_sem(1), num2str(margParam_SF_med(1, :), ' %.2f')));
xlabel('Log Spatial frequency (cpd)'); ylabel('Amplitude');
yticks(-.1:.1:.6)

% SF tuning (full set)
subplot(2,2,4); hold on;
plot(xSF, margSF_med(2, :), 'ko-', 'MarkerFaceColor', 'w');
plot(xSF, margPred_SF_med(2, :), 'k-', 'LineWidth', 2);
xline(1, 'k--', 'LineWidth', 1); % SF=2 cpd
yline(0, 'k--', 'LineWidth', 1); % Marginalized kernel=0
title(sprintf('SF tuning function (full set)\nR2=%.2f (+-%.2f)| Params=[%s]', margR2_SF_med(2), margR2_SF_sem(2), num2str(margParam_SF_med(2, :), ' %.2f')));
xlabel('Log Spatial frequency (cpd)'); ylabel('Amplitude');
yticks(-.1:.1:.6)

sgtitle(sprintf('Figure 3. Tuning functions\n%s (L%d, ModelA%d %s, nIter=%d)', ...
    subjName, iLocComb, iModelA, namesModelA{iModelA}, nIter))

set(findall(gcf, '-property', 'fontsize'), 'fontsize', 20)
% set(findall(gcf, '-property', 'linewidth'), 'linewidth', 2)

saveas(gcf, sprintf('%s/3TuningFxn_L%d_A%d.jpg', nameFolder_Figures_perSubj, iLocComb, iModelA))
