%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOMplot_compDV.m
% Author: Shutian Xue
% Date: August 27, 2025
% ------------------------------------------------------------
% Purpose:
%  Visualize the outputs generated by OOD_NOM_Trialwise_compDV.m.
%  This includes distributions of the internal variable (DV), trial counts per bin,
%  and performance metrics across iterations, as well as the 2D kernel visualization.
%
% Usage:
%  Run this script after executing OOD_NOM_Trialwise_compDV.m and loading its output.
%  The script expects variables such as data_allB, data_metrics_allIter, kernel2D, axis_tuning,
%  axisTicks_tuning, axisTL_tuning, and namesMetrics to be available in the workspace.
%
% Inputs:
%  - data_allB: cell array containing DV, bin counts, and trial data for each iteration
%  - data_metrics_allIter: matrix of performance metrics for each iteration
%  - kernel2D: 2D kernel matrix
%  - axis_tuning, axisTicks_tuning, axisTL_tuning: axis info for kernel plot
%  - namesMetrics: cell array of metric names
%
% Outputs:
%  - Figures visualizing DV distributions, bin counts, performance metrics, and kernel2D
%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Visualizes the output generated by OOD_NOM_Trialwise_compDV.m
% This script is intended to be called after running OOD_NOM_Trialwise_compDV.m
% It loads the saved output and generates plots for DV distribution, bin counts, and performance metrics.

set(0, 'DefaultFigureVisible', 'off') % avoid printing figures on the desktop

xORI = axis_tuning{1}; xSF = axis_tuning{2};

%% Figure 1: Performance Metrics across Iterations
% figure('Position', [100, 100, 2e3, 2e3])
% for iMetric = 1:nMetrics
%     subplot(3, 4, iMetric), hold on
%
%     [metric_med, ~, ~, metric_sem_neg, metric_sem_pos] = getCI(data_metrics_allIter(:, :, iMetric), 1, 1);
%
%     for iDataset = 1:nDatasets % iDataset: 1=full, 2=tmpl, 3=train, 4=test
%         if iDataset==1, color_face = 'k'; else, color_face = 1-ratio_split(iDataset-1)*ones(1,3); end
%         bar(iDataset, metric_med(iDataset), 'EdgeColor', 'k', 'FaceColor', color_face)
%         errorbar(iDataset, metric_med(iDataset), metric_sem_neg, metric_sem_pos, 'k', 'capsize', 0)
%     end
%
%     xticks(1:nDatasets)
%     xticklabels(namesDataset_full)
%     % ylabel(namesMetrics{iMetric})
%     title(namesMetrics{iMetric})
%
%     % Set y-axis limits based on metric type
%     switch iMetric
%         % metrics: [dprime, criterion, [pC, pHit, pFA], nanmean(respC), pYES, mean(1./contrast), median(RT)];
%         case 1, ylimits = [0,2]; yline(dprime_theo, 'k--'); % dprime
%         case 2, ylimits = [-1,1]; yline(0, 'k--'); % criterion
%         case 3, ylimits = [0,1]; yline(.7, 'k--'); % pC; pC_titrate = 0.7 (defined in OOD_sim)
%         case 4, ylimits = [.5, 1]; % pHit
%         case 5, ylimits = [0, .5]; % pFA
%         case 6, ylimits = [.5, 1]; % pA
%         case 7, ylimits = [.5, 1]; % pA1
%         case 8, ylimits = [.5, 1]; % pA0
%         case 9, ylimits = [0, 1]; yline(.5, 'k--'); % pYES
%         case 10, ylimits = [2, 3]; % CS
%         case 11, ylimits = [0, .5]; % RT
%     end
%     ylim(ylimits)
% end
%
% set(findall(gcf, '-property', 'fontsize'), 'fontsize', 15)
% set(findall(gcf, '-property', 'linewidth'), 'linewidth', 2)
%
% sgtitle(sprintf('Figure 1. Measured metrics (Ave across %d iterations +- 68%% CI)\n%s (Loc%d ModelA%d %s)', nIter, subjName, iLocComb, iModelA_fit, namesModelA{iModelA_fit}))
% saveas(gcf, sprintf('%s/11MetricMeasured_L%d_A%d.jpg', nameFolder_Figures_perSubj, iLocComb, iModelA_fit))

%% Figure 2: 2D Template
template_tmpl_ave = squeeze(mean(template_tmpl_allIter, 1));
template_full_ave = squeeze(mean(template_full_allIter, 1));

% template_tmpl_ave = template_tmpl_ave / norm(template_tmpl_ave(:));
% template_full_ave = template_full_ave / norm(template_full_ave(:));

figure('Position', [100, 100, 2e3, 2e3])

subplot(2,3,1), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_ideal); axis square; colorbar; %clim([0, .2])
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('True template')

subplot(2,3,2), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_tmpl_ave); axis square; colorbar; %clim([0, .2])
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('Template derived from TEMPLATE-set trials')

subplot(2,3,3), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_tmpl_ave - template_ideal); axis square; colorbar;
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('Difference with the true template')

subplot(2,3,4), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_tmpl_ave - template_full_ave); axis square; colorbar;
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('Template-set template minus full-set template')

subplot(2,3,5), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_full_ave); axis square; colorbar; %clim([0, .2])
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('Template derived from FULL-set trials')

subplot(2,3,6), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_full_ave - template_ideal); axis square; colorbar;
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('Difference with the true template')

% Calculate Pearson's corr
r_allIter = nan(nIter, 1);
p_allIter = r_allIter;
for iIter = 1:nIter
    kA = template_full_allIter(iIter, :, :);
    kA = kA(:);
    kB = template_ideal(:);
    [r, p] = corr(kA, kB);
    r_allIter(iIter) = r;
    p_allIter(iIter) = p;
end
[r_med, ~, ~, r_SEM] = getCI(r_allIter, 1, 1);
[p_med, ~, ~, p_SEM] = getCI(p_allIter, 1, 1);

sgtitle(sprintf('Figure 2. Recovered template\n%s\nL%d | ModelA%d [%s-derived] | nIter=%d | nBasisORI=%d (chosen %.0f%% iter.) | nBasisSF=%d (chosen %.0f%% iter.)\nMedian Pearson''s corr: r=%.2f (%.2f), p=%.3f (%.3f)', ...
    subjName, iLocComb, iModelA_fit, namesModelA{iModelA_fit}, nIter, ...
    mode(nBasisORI_tmpl_allIter), mean(nBasisORI_tmpl_allIter == mode(nBasisORI_tmpl_allIter))*100, ...
    mode(nBasisSF_tmpl_allIter), mean(nBasisSF_tmpl_allIter == mode(nBasisSF_tmpl_allIter))*100, ...
    r_med, r_SEM, p_med, p_SEM))

set(findall(gcf, '-property', 'fontsize'), 'fontsize', 15)
set(findall(gcf, '-property', 'linewidth'), 'linewidth',2)

saveas(gcf, sprintf('%s/12Template_L%d_A%d.jpg', nameFolder_Figures_perSubj, iLocComb, iModelA_fit))

%% Figure 3. Plot marg and margPred, print R2 and params in the title
if iModelA_fit==1 % data-derived template
    [margORI_med, ~, ~, margORI_sem] = getCI(margORI_allIter, 1, 1);
    [margSF_med, ~, ~, margSF_sem] = getCI(margSF_allIter, 1, 1);

    [margPred_ORI_med, ~, ~, margPred_ORI_sem] = getCI(margPred_ORI_allIter, 1, 1);
    [margPred_SF_med, ~, ~, margPred_SF_sem] = getCI(margPred_SF_allIter, 1, 1);

    [margParam_ORI_med, ~, ~, margParam_ORI_sem] = getCI(margParams_ORI_allIter, 1, 1);
    [margParam_SF_med, ~, ~, margParam_SF_sem] = getCI(margParams_SF_allIter, 1, 1);

    [margR2_ORI_med, ~, ~, margR2_ORI_sem] = getCI(margR2_ORI_allIter, 1, 1);
    [margR2_SF_med, ~, ~, margR2_SF_sem] = getCI(margR2_SF_allIter, 1, 1);

    % Process the ideal template
    margIO_ORI = mean(template_ideal, 2);
    margIO_ORI_norm_tmpl = margIO_ORI/max(margIO_ORI(:))*max(margORI_med(1, :));
    margIO_ORI_norm_full = margIO_ORI/max(margIO_ORI(:))*max(margORI_med(2, :));

    margIO_SF = mean(template_ideal, 1);
    margIO_SF_norm_tmpl = margIO_SF/max(margIO_SF(:))*max(margSF_med(1, :));
    margIO_SF_norm_full = margIO_SF/max(margIO_SF(:))*max(margSF_med(2, :));

    figure('Position', [0 0 1e3 1e3])
    % ORI tuning (template set)
    subplot(2,2,1); hold on;
    plot(xORI, margORI_med(1, :)/max(margORI_med(1, :)), 'ko-', 'MarkerFaceColor', 'w');
    plot(xORI, margPred_ORI_med(1, :)/max(margPred_ORI_med(1, :)), 'k-', 'LineWidth', 2);
    plot(xORI, margIO_ORI_norm_tmpl/max(margIO_ORI_norm_tmpl), 'r-', 'LineWidth', 2); % ideal template
    xline(0, 'k--', 'LineWidth', 1); % ORI=0
    yline(0, 'k--', 'LineWidth', 1); % Marginalized kernel=0
    title(sprintf('ORI tuning function (template set)\nR2=%.2f (+-%.2f)| Params=[%s ]', margR2_ORI_med(1), margR2_ORI_sem(1), num2str(margParam_ORI_med(1, :), ' %.2f')));
    xlabel('Orientation (deg)'); ylabel('Amplitude');
    % yticks(-.1:.1:1)
    ylim([-.2, 1])
    legend({'Marg. ORI', 'Pred', 'Ideal'})

    % ORI tuning (full set)
    subplot(2,2,3); hold on;
    plot(xORI, margORI_med(2, :)/max(margORI_med(2, :)), 'ko-', 'MarkerFaceColor', 'w');
    plot(xORI, margPred_ORI_med(2, :)/max(margPred_ORI_med(2, :)), 'k-', 'LineWidth', 2);
    plot(xORI, margIO_ORI_norm_full/max(margIO_ORI_norm_full), 'r-', 'LineWidth', 2); % ideal template
    xline(0, 'k--', 'LineWidth', 1); % ORI=0
    yline(0, 'k--', 'LineWidth', 1); % Marginalized kernel=0
    title(sprintf('ORI tuning function (full set)\nR2=%.2f (+-%.2f)| Params=[%s ]', margR2_ORI_med(2), margR2_ORI_sem(2), num2str(margParam_ORI_med(2, :), ' %.2f')));
    xlabel('Orientation (deg)'); ylabel('Amplitude');
    % yticks(-.1:.1:1)
    ylim([-.2, 1])

    % SF tuning (template set)
    subplot(2,2,2); hold on;
    plot(xSF, margSF_med(1, :)/max(margSF_med(1, :)), 'ko-', 'MarkerFaceColor', 'w');
    plot(xSF, margPred_SF_med(1, :)/max(margPred_SF_med(1, :)), 'k-', 'LineWidth', 2);
    plot(xSF, margIO_SF_norm_tmpl/max(margIO_SF_norm_tmpl), 'r-', 'LineWidth', 2); % ideal template
    xline(1, 'k--', 'LineWidth', 1); % SF=2 cpd
    yline(0, 'k--', 'LineWidth', 1); % Marginalized kernel=0
    title(sprintf('SF tuning function (template set)\nR2=%.2f (+-%.2f)| Params=[%s]', margR2_SF_med(1), margR2_SF_sem(1), num2str(margParam_SF_med(1, :), ' %.2f')));
    xlabel('Log Spatial frequency (cpd)'); ylabel('Amplitude');
    % yticks(-.1:.1:.6)
    ylim([-.2, 1])

    % SF tuning (full set)
    subplot(2,2,4); hold on;
    plot(xSF, margSF_med(2, :)/max(margSF_med(2, :)), 'ko-', 'MarkerFaceColor', 'w');
    plot(xSF, margPred_SF_med(2, :)/max(margPred_SF_med(2, :)), 'k-', 'LineWidth', 2);
    plot(xSF, margIO_SF_norm_full/max(margIO_SF_norm_full), 'r-', 'LineWidth', 2); % ideal template
    xline(1, 'k--', 'LineWidth', 1); % SF=2 cpd
    yline(0, 'k--', 'LineWidth', 1); % Marginalized kernel=0
    title(sprintf('SF tuning function (full set)\nR2=%.2f (+-%.2f)| Params=[%s]', margR2_SF_med(2), margR2_SF_sem(2), num2str(margParam_SF_med(2, :), ' %.2f')));
    xlabel('Log Spatial frequency (cpd)'); ylabel('Amplitude');
    % yticks(-.1:.1:.6)
    ylim([-.2, 1])

    sgtitle(sprintf('Figure 3. Tuning functions\n%s (L%d, ModelA%d %s, nIter=%d)', ...
        subjName, iLocComb, iModelA_fit, namesModelA{iModelA_fit}, nIter))

    set(findall(gcf, '-property', 'fontsize'), 'fontsize', 12)
    % set(findall(gcf, '-property', 'linewidth'), 'linewidth', 2)

    saveas(gcf, sprintf('%s/13TuningFxn_L%d_A%d.jpg', nameFolder_Figures_perSubj, iLocComb, iModelA_fit))
end


%% Figure 4: Plot rank of selected basis counts / families / width scales / ridge across iterations

% if ~exist('asymSF_rightLeftRatio_tmpl_allIter', 'var')
%     asymSF_rightLeftRatio_tmpl_allIter = nan(size(nBasisSF_tmpl_allIter));
% end
%
% figure('Position', [100 100 1600 800]);
% % tiledlayout(3, 3, 'TileSpacing', 'compact', 'Padding', 'compact');
%
% % ---------- 1. nBasisORI ----------
% subplot(2,4,1); hold on;
% plot_ranked_categorical(nBasisORI_tmpl_allIter, 'nBasisORI');
% ylabel('% iterations selected');
% title('nBasisORI');
% box on;
%
% % ---------- 2. nBasisSF ----------
% subplot(2,4,5); hold on;
% plot_ranked_categorical(nBasisSF_tmpl_allIter, 'nBasisSF');
% ylabel('% iterations selected');
% title('nBasisSF');
% box on;
%
% % ---------- 3. basisFxnORI ----------
% subplot(2,4,2); hold on;
% plot_ranked_categorical(basisFxnORI_tmpl_allIter, 'basisFxnORI');
% ylabel('% iterations selected');
% title('basisFxnORI');
% box on;
%
% % ---------- 4. basisFxnSF ----------
% subplot(2,4,6); hold on;
% plot_ranked_categorical(basisFxnSF_tmpl_allIter, 'basisFxnSF');
% ylabel('% iterations selected');
% title('basisFxnSF');
% box on;
%
% % ---------- 5. basisWidthScaleORI ----------
% subplot(2,4,3); hold on;
% plot_ranked_categorical(basisWidthScaleORI_tmpl_allIter, 'basisWidthScaleORI');
% ylabel('% iterations selected');
% title('basisWidthScaleORI');
% box on;
%
% % ---------- 6. basisWidthScaleSF ----------
% subplot(2,4,7); hold on;
% plot_ranked_categorical(basisWidthScaleSF_tmpl_allIter, 'basisWidthScaleSF');
% ylabel('% iterations selected');
% title('basisWidthScaleSF');
% box on;
%
% % ---------- 7. ridge ----------
% subplot(2,4,4); hold on;
% plot_ranked_categorical(ridge_tmpl_allIter, 'ridge');
% ylabel('% iterations selected');
% title('ridge');
% box on;
%
% % ---------- 8. asymSF_rightLeftRatio ----------
% subplot(2,4,8); hold on;
% plot_ranked_categorical(asymSF_rightLeftRatio_tmpl_allIter, 'asymSF_rightLeftRatio');
% ylabel('% iterations selected');
% title('asymSF_rightLeftRatio');
% box on;
%
% sgtitle('Rank of selected basis settings across iterations');
%
% saveas(gcf, sprintf('%s/14SelectedBasis_L%d_A%d.jpg', nameFolder_Figures_perSubj, iLocComb, iModelA_fit))

%% ---------- local helper ----------
function plot_ranked_categorical(vals, xLabelText)

    % convert input to string labels
    if isnumeric(vals) || islogical(vals)
        vals = vals(:);
        vals = vals(isfinite(vals));
        labels = string(vals);

    elseif iscell(vals)
        labels = string(vals(:));
        labels = labels(strlength(labels) > 0);

    elseif isstring(vals) || iscategorical(vals)
        labels = string(vals(:));
        labels = labels(strlength(labels) > 0);

    else
        error('Unsupported type for ranked categorical plot.');
    end

    if isempty(labels)
        text(0.5, 0.5, 'No data', 'HorizontalAlignment', 'center');
        xlim([0 1]); ylim([0 1]);
        return
    end

    % count frequencies
    [u, ~, ic] = unique(labels);
    counts = accumarray(ic, 1);
    pct = counts / sum(counts) * 100;

    % sort high to low
    [pct_sorted, idxSort] = sort(pct, 'descend');
    u_sorted = u(idxSort);

    % bar plot
    bar(1:numel(u_sorted), pct_sorted, 0.7);
    xticks(1:numel(u_sorted));
    xticklabels(u_sorted);
    xtickangle(45);
    xlabel(xLabelText);
    ylim([0, max(pct_sorted)*1.15]);

    % annotate percentage
    for i = 1:numel(u_sorted)
        text(i, pct_sorted(i), sprintf(' %.0f%%', pct_sorted(i)), ...
            'VerticalAlignment', 'bottom', ...
            'HorizontalAlignment', 'left', ...
            'FontSize', 9);
    end
end
