%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOMplot_compIV.m
% Author: Shutian Xue
% Date: August 27, 2025
% ------------------------------------------------------------
% Purpose:
%   Visualize the outputs generated by OOD_NOM_Trialwise_compIV.m.
%   This includes distributions of the internal variable (IV), trial counts per bin,
%   and performance metrics across iterations, as well as the 2D kernel visualization.
%
% Usage:
%   Run this script after executing OOD_NOM_Trialwise_compIV.m and loading its output.
%   The script expects variables such as data_allB, data_metrics_allB, kernel2D, axis_tuning,
%   axisTicks_tuning, axisTL_tuning, and namesMetrics to be available in the workspace.
%
% Inputs:
%   - data_allB: cell array containing IV, bin counts, and trial data for each iteration
%   - data_metrics_allB: matrix of performance metrics for each iteration
%   - kernel2D: 2D kernel matrix
%   - axis_tuning, axisTicks_tuning, axisTL_tuning: axis info for kernel plot
%   - namesMetrics: cell array of metric names
%
% Outputs:
%   - Figures visualizing IV distributions, bin counts, performance metrics, and kernel2D
%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Visualizes the output generated by OOD_NOM_Trialwise_compIV.m
% This script is intended to be called after running OOD_NOM_Trialwise_compIV.m
% It loads the saved output and generates plots for IV distribution, bin counts, and performance metrics.

%% Figure 1: Performance Metrics across Iterations
figure('Position', [100, 100, 2e3, 2e3])
for iMetric = 1:nmetrics
    subplot(3,3,iMetric)
    plot(data_metrics_allB(:,iMetric),'-o');
    yline(getCI(data_metrics_allB(:,iMetric), 1, 1),'k-');
    xlabel('Iteration');
    ylabel(namesMetrics{iMetric})
    title(sprintf('Metric %s across iterations', namesMetrics{iMetric}));
    % Set y-axis limits based on metric type
    switch iMetric
        case 1, ylimits = [0,2]; % dprime
        case 2, ylimits = [-1,1]; yline(0, 'k--'); % criterion
        case 3, ylimits = [0,1]; yline(.7, 'k--'); % pC; pC_titrate = 0.7 (defined in OOD_sim)
        case 4, ylimits = [0,1]; % pHit
        case 5, ylimits = [0,1]; % pFA
        case 6, ylimits = [.5,1]; % pA
        case 7, ylimits = [.5,1]; % pA1
        case 8, ylimits = [.5,1]; % pA0
        case 9, ylimits = [0,1]; % pYES
    end
    ylim(ylimits)
end
set(findall(gcf, '-property', 'fontsize'), 'fontsize', 15)
set(findall(gcf, '-property', 'linewidth'), 'linewidth',2)
% saveas(gcf, sprintf('%s/1PerfPerIteraction.jpg', nameFolder_Figures_local))
sgtitle(sprintf('Figure 1. Measured metrics as a fxn of iteration\n%s (ModelA%d %s, niterations=%d)', ...
    subjName, iModelA, namesModelA{iModelA}, nIterations))
saveas(gcf, sprintf('%s/1MetricMeasured_%s_A%d.jpg', nameFolder_Figures_NOM, subjName, iModelA))

%% Figure 2: 2D Kernel

% if exist('template_true', 'var')
    kernel2D_ave = squeeze(mean(kernel2D_allB, 1));

    figure('Position', [100, 100, 2e3, 600])

    subplot(1,3,1), hold on
    imagesc(axis_tuning{2}, axis_tuning{1}, template_true), axis square, colorbar, %clim([0, .2])
    xline(1, 'r-'); % log gabor SF
    yline(0, 'r-'); % Gabor ori
    xlabel('Spatial Frequency'), ylabel('Orientation')
    xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
    yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
    title('True template')

    subplot(1,3,2), hold on
    imagesc(axis_tuning{2}, axis_tuning{1}, kernel2D_ave), axis square, colorbar, %clim([0, .2])
    xline(1, 'r-'); % log gabor SF
    yline(0, 'r-'); % Gabor ori
    xlabel('Spatial Frequency'), ylabel('Orientation')
    xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
    yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
    title(sprintf('Derived template (averaged across %d iterations)', nIterations))

    subplot(1,3,3), hold on
    imagesc(axis_tuning{2}, axis_tuning{1}, kernel2D_ave-template_true), axis square, colorbar
    xline(1, 'r-'); % log gabor SF
    yline(0, 'r-'); % Gabor ori
    xlabel('Spatial Frequency'), ylabel('Orientation')
    xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
    yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
    title('Difference between the derived and the true template')

    set(findall(gcf, '-property', 'fontsize'), 'fontsize', 15)
    set(findall(gcf, '-property', 'linewidth'), 'linewidth',2)

    % Calculate Pearson's corr
    r_all = nan(nIterations, 1);
    p_all = r_all;
    for ii = 1:nIterations
        kA = kernel2D_allB(ii, :, :);
        kA = kA(:);
        kB = template_true(:);
        [r, p] = corr(kA, kB);
        r_all(ii) = r;
        p_all(ii) = p;
    end
    [r_ave, ~, ~, r_SEM] = getCI(r_all, 2, 1);
    [p_ave, ~, ~, p_SEM] = getCI(p_all, 2, 1);
    

    sgtitle(sprintf('Figure 2. Recovered template\n%s (ModelA%d %s, niterations=%d)\nAveraged Pearson''s corr: r=%.2f (%.2f), p=%.3f (%.2f)', ...
    subjName, iModelA, namesModelA{iModelA}, nIterations, r_ave, r_SEM, p_ave, p_SEM))

    % saveas(gcf, sprintf('%s/2RecoveredTemplate_AveIteraction_%s_A%dB%d.jpg', nameFolder_Figures_local))
    saveas(gcf, sprintf('%s/2Template_%s_A%d.jpg', nameFolder_Figures_NOM, subjName, iModelA))
    % sgtitle('NOM Trialwise Output Visualization');

% end