%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOMplot_compIV.m
% Author: Shutian Xue
% Date: August 27, 2025
% ------------------------------------------------------------
% Purpose:
%  Visualize the outputs generated by OOD_NOM_Trialwise_compIV.m.
%  This includes distributions of the internal variable (IV), trial counts per bin,
%  and performance metrics across iterations, as well as the 2D kernel visualization.
%
% Usage:
%  Run this script after executing OOD_NOM_Trialwise_compIV.m and loading its output.
%  The script expects variables such as data_allB, data_metrics_allBoot, kernel2D, axis_tuning,
%  axisTicks_tuning, axisTL_tuning, and namesMetrics to be available in the workspace.
%
% Inputs:
%  - data_allB: cell array containing IV, bin counts, and trial data for each iteration
%  - data_metrics_allBoot: matrix of performance metrics for each iteration
%  - kernel2D: 2D kernel matrix
%  - axis_tuning, axisTicks_tuning, axisTL_tuning: axis info for kernel plot
%  - namesMetrics: cell array of metric names
%
% Outputs:
%  - Figures visualizing IV distributions, bin counts, performance metrics, and kernel2D
%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Visualizes the output generated by OOD_NOM_Trialwise_compIV.m
% This script is intended to be called after running OOD_NOM_Trialwise_compIV.m
% It loads the saved output and generates plots for IV distribution, bin counts, and performance metrics.

%% Figure 1: Performance Metrics across Iterations
figure('Position', [100, 100, 2e3, 2e3])
for iMetric = 1:nmetrics
    subplot(3,3,iMetric)
    plot(data_metrics_allBoot(:,iMetric),'-o');
    yline(getCI(data_metrics_allBoot(:,iMetric), 1, 1),'k-');
    xlabel('Iteration');
    ylabel(namesMetrics{iMetric})
    title(sprintf('Metric %s across iterations', namesMetrics{iMetric}));
    % Set y-axis limits based on metric type
    switch iMetric
        case 1, ylimits = [0,2]; % dprime
        case 2, ylimits = [-1,1]; yline(0, 'k--'); % criterion
        case 3, ylimits = [0,1]; yline(.7, 'k--'); % pC; pC_titrate = 0.7 (defined in OOD_sim)
        case 4, ylimits = [0,1]; % pHit
        case 5, ylimits = [0,1]; % pFA
        case 6, ylimits = [.5,1]; % pA
        case 7, ylimits = [.5,1]; % pA1
        case 8, ylimits = [.5,1]; % pA0
        case 9, ylimits = [0,1]; % pYES
    end
    ylim(ylimits)
end
set(findall(gcf, '-property', 'fontsize'), 'fontsize', 15)
set(findall(gcf, '-property', 'linewidth'), 'linewidth',2)
% saveas(gcf, sprintf('%s/1PerfPerIteraction.jpg', nameFolder_Figures_local))
sgtitle(sprintf('Figure 1. Measured metrics as a fxn of iteration\n%s (L%d ModelA%d %s, nBoot=%d)', ...
    subjName, iLocComb, iModelA, namesModelA{iModelA}, nBoot))
saveas(gcf, sprintf('%s/1MetricMeasured_%s_L%d_A%d.jpg', nameFolder_Figures_NOM, subjName, iLocComb, iModelA))

%% Figure 2: 2D Kernel
template_train_ave = squeeze(mean(template_train_allBoot, 1));
template_full_ave = squeeze(mean(template_full_allBoot, 1));

figure('Position', [100, 100, 2e3, 2e3])

subplot(2,3,1), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_true), axis square, colorbar, %clim([0, .2])
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('True template')

subplot(2,3,2), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_train_ave), axis square, colorbar, %clim([0, .2])
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('Template derived from TRAINING trials')

subplot(2,3,3), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_train_ave-template_true), axis square, colorbar
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('Difference with the true template')

subplot(2,3,4), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_train_ave-template_full_ave), axis square, colorbar
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('Full template-training template')

subplot(2,3,5), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_full_ave), axis square, colorbar, %clim([0, .2])
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('Template derived from ALL trials')

subplot(2,3,6), hold on
imagesc(axis_tuning{2}, axis_tuning{1}, template_full_ave-template_true), axis square, colorbar
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title('Difference with the true template')

set(findall(gcf, '-property', 'fontsize'), 'fontsize', 15)
set(findall(gcf, '-property', 'linewidth'), 'linewidth',2)

% Calculate Pearson's corr
r_all = nan(nBoot, 1);
p_all = r_all;
for ii = 1:nBoot
    kA = template_full_allBoot(ii, :, :);
    kA = kA(:);
    kB = template_true(:);
    [r, p] = corr(kA, kB);
    r_all(ii) = r;
    p_all(ii) = p;
end
[r_ave, ~, ~, r_SEM] = getCI(r_all, 2, 1);
[p_ave, ~, ~, p_SEM] = getCI(p_all, 2, 1);

sgtitle(sprintf('Figure 2. Recovered template\n%s (L%d, ModelA%d %s, nBoot=%d)\nAveraged Pearson''s corr: r=%.2f (%.2f), p=%.3f (%.2f)', ...
    subjName, iLocComb, iModelA, namesModelA{iModelA}, nBoot, r_ave, r_SEM, p_ave, p_SEM))

saveas(gcf, sprintf('%s/2Template_%s_L%d_A%d.jpg', nameFolder_Figures_NOM, subjName, iLocComb, iModelA))

%% Figure 3. Plot marg and margPred, print R2 and params in the title
[margORI_med, ~, ~, margORI_sem] = getCI(margORI_allBoot, 1, 1);
[margSF_med, ~, ~, margSF_sem] = getCI(margSF_allBoot, 1, 1);

[margPred_ORI_med, ~, ~, margPred_ORI_sem] = getCI(margPred_ORI_allBoot, 1, 1);
[margPred_SF_med, ~, ~, margPred_SF_sem] = getCI(margPred_SF_allBoot, 1, 1);

[margParam_ORI_med, ~, ~, margParam_ORI_sem] = getCI(margParams_ORI_allBoot, 1, 1);
[margParam_SF_med, ~, ~, margParam_SF_sem] = getCI(margParams_SF_allBoot, 1, 1);

[margR2_ORI_med, ~, ~, margR2_ORI_sem] = getCI(margR2_ORI_allBoot, 1, 1);
[margR2_SF_med, ~, ~, margR2_SF_sem] = getCI(margR2_SF_allBoot, 1, 1);

figure('Position', [0 0 1e3 1e3])
% ORI tuning (training set)
subplot(2,2,1); hold on;
plot(xORI, margORI_med(1, :), 'ko-', 'MarkerFaceColor', 'w');
plot(xORI, margPred_ORI_med(1, :), 'k-', 'LineWidth', 2);
xline(0, 'k--', 'LineWidth', 1); % ORI=0
yline(0, 'k--', 'LineWidth', 1); % Marginalized kernel=0
title(sprintf('ORI tuning function (training set)\nR2=%.2f (+-%.2f)| Params=[%s ]', margR2_ORI_med(1), margR2_ORI_sem(1), num2str(margParam_ORI_med(1, :), ' %.2f')));
xlabel('Orientation (deg)'); ylabel('Amplitude');

% ORI tuning (full set)
subplot(2,2,3); hold on;
plot(xORI, margORI_med(2, :), 'ko-', 'MarkerFaceColor', 'w');
plot(xORI, margPred_ORI_med(2, :), 'k-', 'LineWidth', 2);
xline(0, 'k--', 'LineWidth', 1); % ORI=0
yline(0, 'k--', 'LineWidth', 1); % Marginalized kernel=0
title(sprintf('ORI tuning function (full set)\nR2=%.2f (+-%.2f)| Params=[%s ]', margR2_ORI_med(2), margR2_ORI_sem(2), num2str(margParam_ORI_med(2, :), ' %.2f')));
xlabel('Orientation (deg)'); ylabel('Amplitude');

% SF tuning (training set)
subplot(2,2,2); hold on;
plot(xSF, margSF_med(1, :), 'ko-', 'MarkerFaceColor', 'w');
plot(xSF, margPred_SF_med(1, :), 'k-', 'LineWidth', 2);
xline(1, 'k--', 'LineWidth', 1); % SF=2 cpd
yline(0, 'k--', 'LineWidth', 1); % Marginalized kernel=0
title(sprintf('SF tuning function (training set)\nR2=%.2f (+-%.2f)| Params=[%s]', margR2_SF_med(1), margR2_SF_sem(1), num2str(margParam_SF_med(1, :), ' %.2f')));
xlabel('Log Spatial frequency (cpd)'); ylabel('Amplitude');

% SF tuning (full set)
subplot(2,2,4); hold on;
plot(xSF, margSF_med(2, :), 'ko-', 'MarkerFaceColor', 'w');
plot(xSF, margPred_SF_med(2, :), 'k-', 'LineWidth', 2);
xline(1, 'k--', 'LineWidth', 1); % SF=2 cpd
yline(0, 'k--', 'LineWidth', 1); % Marginalized kernel=0
title(sprintf('SF tuning function (full set)\nR2=%.2f (+-%.2f)| Params=[%s]', margR2_SF_med(2), margR2_SF_sem(2), num2str(margParam_SF_med(2, :), ' %.2f')));
xlabel('Log Spatial frequency (cpd)'); ylabel('Amplitude');

sgtitle(sprintf('Figure 3. Tuning functions\n%s (L%d, ModelA%d %s, nBoot=%d)', ...
    subjName, iLocComb, iModelA, namesModelA{iModelA}, nBoot))

set(findall(gcf, '-property', 'fontsize'), 'fontsize', 20)
% set(findall(gcf, '-property', 'linewidth'), 'linewidth', 2)

saveas(gcf, sprintf('%s/3TuningFxn_%s_L%d_A%d.jpg', nameFolder_Figures_NOM, subjName, iLocComb, iModelA))
