%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOMplot_beforeEst.m
% Author: Shutian Xue
% Date: August 27, 2025
% ------------------------------------------------------------
% Purpose:
%   Visualize the outputs generated by OOD_NOM_Trialwise_beforeEst.m.
%   This includes distributions of the internal variable (IV), trial counts per bin,
%   and performance metrics across iterations, as well as the 2D kernel visualization.
%
% Usage:
%   Run this script after executing OOD_NOM_Trialwise_beforeEst.m and loading its output.
%   The script expects variables such as data_allB, data_metrics_allB, kernel2D, axis_tuning,
%   axisTicks_tuning, axisTL_tuning, and namesMetrics to be available in the workspace.
%
% Inputs:
%   - data_allB: cell array containing IV, bin counts, and trial data for each iteration
%   - data_metrics_allB: matrix of performance metrics for each iteration
%   - kernel2D: 2D kernel matrix
%   - axis_tuning, axisTicks_tuning, axisTL_tuning: axis info for kernel plot
%   - namesMetrics: cell array of metric names
%
% Outputs:
%   - Figures visualizing IV distributions, bin counts, performance metrics, and kernel2D
%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Visualizes the output generated by OOD_NOM_Trialwise_beforeEst.m
% This script is intended to be called after running OOD_NOM_Trialwise_beforeEst.m
% It loads the saved output and generates plots for IV distribution, bin counts, and performance metrics.

%% Figure 1: Distribution of IV and Trial Counts per bins for each iteration
figure('Position', [100, 100, 1200, 600])
for ii = 1:ni
    data = data_allB{ii};
    subplot(1,2,1); hold on;
    % histogram(data.IV, 'Normalization','probability');
    histogram(nthroot(data.IV-min(data.IV),2), 'Normalization','probability');
    title('Distribution of Internal Variable (IV) (Each color is a different iteration)');
    xlabel('IV'); ylabel('Probability');

    [h, pValue, Wstat] = swtest(nthroot(data.IV-min(data.IV),2), 0.05)

    subplot(1,2,2); hold on;
    bar(data.nTrials_allBins);
    title('Trial Counts per Bin (Each color is a different iteration)');
    xlabel('Bin #'); ylabel('Number of trials');
end
set(findall(gcf, '-property', 'fontsize'), 'fontsize', 15)
set(findall(gcf, '-property', 'linewidth'), 'linewidth',2)

%% Figure 2: Performance Metrics across Iterations
figure('Position', [100, 100, 2e3, 2e3])
for iMetric = 1:nmetrics
    subplot(2,4,iMetric)
    plot(data_metrics_allB(:,iMetric),'-o');
    xlabel('Iteration'); 
    ylabel(namesMetrics{iMetric})
    title(sprintf('Metric %s across iterations', namesMetrics{iMetric}));
    % Set y-axis limits based on metric type
    switch iMetric
        case 1, ylimits = [0,2]; % dprime
        case 2, ylimits = [-1,1]; yline(0, 'k--'); % criterion
        case 3, ylimits = [0,1]; yline(.7, 'k--'); % pC; pC_titrate = 0.7 (defined in OOD_sim)
        case 4, ylimits = [0,1]; % pHit
        case 5, ylimits = [0,1]; % pFA
        case 6, ylimits = [.5,1]; % pA
        case 7, ylimits = [.5,1]; % pA1
        case 8, ylimits = [.5,1]; % pA0
    end
    ylim(ylimits)
end
set(findall(gcf, '-property', 'fontsize'), 'fontsize', 15)
set(findall(gcf, '-property', 'linewidth'), 'linewidth',2)

%% Figure 3: 2D Kernel Visualization
kernel2D_ave = squeeze(mean(kernel2D_all, 1));

figure('Position', [100, 100, 600, 600])   
imagesc(axis_tuning{2}, axis_tuning{1}, kernel2D_ave), axis square
xline(1, 'r-'); % log gabor SF
yline(0, 'r-'); % Gabor ori
xlabel('Spatial Frequency'), ylabel('Orientation')
xticks(axisTicks_tuning{2}), xticklabels(axisTL_tuning{2})
yticks(axisTicks_tuning{1}), yticklabels(axisTL_tuning{1})
title(sprintf('Template derived from the training set via RC (averaged across %d iterations)', ni))
set(findall(gcf, '-property', 'fontsize'), 'fontsize', 20)
set(findall(gcf, '-property', 'linewidth'), 'linewidth',2)

% sgtitle('NOM Trialwise Output Visualization');
