function record = exp_createRecord(params, blank, stairs_all)

design = params.design;

record = struct(...
    'params',params,...
    'iblock_start',1,...
    'iblock_current',1,...
    'thresh_exp',[], ...
    'iStair',blank,...
    'iCuedLoc', blank,...
    'RT', blank,...
    'answer', blank,...
    'correctness', blank,...
    'tgtPrs',blank,...
    'phase_tgt', blank,...
    'accPerBlock',nan(1,design.nBlocks),...
    'dprime',nan(1,design.nBlocks),...
    'criterion',nan(1,design.nBlocks),...
    'repInd', blank, ...
    'run_allTrials',{cell(design.nBlocks, design.nTrialsPerBlock)},...
    'stairs_all', {stairs_all});