#!/bin/bash
#
#SBATCH --nodes=1
#SBATCH --cpus-per-task=12
#SBATCH --mem=10G
#SBATCH --time=1:00:00
#SBATCH --output=zzz_Sim_%j.out
#SBATCH --mail-user=vivanxuest@gmail.com
#SBATCH --mail-type=END

#########performance evaluation########
wk_dir=$(pwd)
bash $wk_dir/evaluation-performance/evaluation-performance.sh $wk_dir/evaluation-performance/
############end########################

module purge
module load matlab/2024b
 export MATLAB_PREFDIR=$(mktemp -d -t matlab-XXXX)

echo
echo "job name: $SLURM_JOB_NAME"

cat<<EOF | srun matlab -nodisplay

%===============
noiseCST=$1;
gaborCST=$2;
nTrials=$3;
noiseP=$4;
iModelB_sim=$5;

OOD_sim(noiseCST, gaborCST, nTrials, noiseP, iModelB_sim)

%===============
exit
EOF
 
rm -rf $MATLAB_PREFDIR
exit
